# Generated by Django 5.2.16 on 2026-07-24 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_operational_metrics_profiles_glpi_import'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='serverprofile',
            name='glpi_managed_fields',
            field=models.JSONField(blank=True, default=list, verbose_name='поля, управляемые GLPI'),
        ),
        migrations.CreateModel(
            name='GlpiCacheSyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trigger', models.CharField(choices=[('manual', 'Вручную'), ('command', 'Командой')], default='manual', max_length=16, verbose_name='источник запуска')),
                ('status', models.CharField(choices=[('running', 'Выполняется'), ('completed', 'Завершён'), ('partial', 'Частично завершён'), ('failed', 'Ошибка')], default='running', max_length=16, verbose_name='статус')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='начат')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='завершён')),
                ('full_computer_list_received', models.BooleanField(default=False, verbose_name='полный список компьютеров получен')),
                ('statistics', models.JSONField(blank=True, default=dict, verbose_name='статистика')),
                ('error_summary', models.TextField(blank=True, verbose_name='сводка ошибок')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requested_glpi_cache_syncs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GlpiCachedLookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('computer_type', 'Тип компьютера'), ('state', 'Статус'), ('location', 'Местоположение'), ('manufacturer', 'Производитель'), ('computer_model', 'Модель компьютера'), ('auto_update_system', 'Источник инвентаризации')], max_length=32, verbose_name='вид справочника')),
                ('external_id', models.CharField(max_length=64, verbose_name='ID GLPI')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='наименование')),
                ('complete_name', models.CharField(blank=True, max_length=500, verbose_name='полное наименование')),
                ('raw_payload', models.JSONField(blank=True, default=dict, verbose_name='сырой JSON')),
                ('is_missing', models.BooleanField(default=False, verbose_name='отсутствует в последней выгрузке')),
                ('last_seen_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seen_lookups', to='catalog.glpicachesyncrun')),
            ],
            options={
                'ordering': ['kind', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GlpiCachedComputer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(max_length=64, unique=True, verbose_name='ID GLPI')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='имя')),
                ('comment', models.TextField(blank=True, verbose_name='комментарий')),
                ('serial_number', models.CharField(blank=True, max_length=255, verbose_name='серийный номер')),
                ('inventory_number', models.CharField(blank=True, max_length=255, verbose_name='инвентарный номер')),
                ('external_uuid', models.CharField(blank=True, max_length=255, verbose_name='UUID')),
                ('external_created_at', models.DateTimeField(blank=True, null=True)),
                ('external_updated_at', models.DateTimeField(blank=True, null=True)),
                ('last_inventory_update', models.DateTimeField(blank=True, null=True)),
                ('last_boot', models.DateTimeField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict, verbose_name='сырой JSON')),
                ('last_successful_sync_at', models.DateTimeField(blank=True, null=True)),
                ('is_missing', models.BooleanField(default=False, verbose_name='отсутствует в последней выгрузке')),
                ('last_error', models.CharField(blank=True, max_length=500)),
                ('auto_update_system', models.ForeignKey(blank=True, limit_choices_to={'kind': 'auto_update_system'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='computers_by_auto_update', to='catalog.glpicachedlookup')),
                ('computer_type', models.ForeignKey(blank=True, limit_choices_to={'kind': 'computer_type'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='computers_by_type', to='catalog.glpicachedlookup')),
                ('location', models.ForeignKey(blank=True, limit_choices_to={'kind': 'location'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='computers_by_location', to='catalog.glpicachedlookup')),
                ('manufacturer', models.ForeignKey(blank=True, limit_choices_to={'kind': 'manufacturer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='computers_by_manufacturer', to='catalog.glpicachedlookup')),
                ('model', models.ForeignKey(blank=True, limit_choices_to={'kind': 'computer_model'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='computers_by_model', to='catalog.glpicachedlookup')),
                ('state', models.ForeignKey(blank=True, limit_choices_to={'kind': 'state'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='computers_by_state', to='catalog.glpicachedlookup')),
                ('last_seen_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seen_computers', to='catalog.glpicachesyncrun')),
            ],
            options={
                'ordering': ['name', 'external_id'],
            },
        ),
        migrations.CreateModel(
            name='GlpiCachedComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('component_key', models.CharField(max_length=64)),
                ('payload', models.JSONField(blank=True, default=list, verbose_name='сырой JSON')),
                ('normalized_payload', models.JSONField(blank=True, default=dict, verbose_name='нормализованные данные')),
                ('source', models.CharField(choices=[('api', 'GLPI API'), ('database', 'База GLPI')], default='api', max_length=16)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_successful_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=500)),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='catalog.glpicachedcomputer')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('computer', 'component_key'), name='catalog_glpi_component_unique')],
            },
        ),
        migrations.AddIndex(
            model_name='glpicachedlookup',
            index=models.Index(fields=['kind', 'is_missing', 'name'], name='catalog_glpi_lookup_filter_idx'),
        ),
        migrations.AddConstraint(
            model_name='glpicachedlookup',
            constraint=models.UniqueConstraint(fields=('kind', 'external_id'), name='catalog_glpi_lookup_unique'),
        ),
        migrations.AddIndex(
            model_name='glpicachedcomputer',
            index=models.Index(fields=['is_missing', 'computer_type'], name='catalog_glpi_comp_type_idx'),
        ),
        migrations.AddIndex(
            model_name='glpicachedcomputer',
            index=models.Index(fields=['is_missing', 'state'], name='catalog_glpi_comp_state_idx'),
        ),
        migrations.AddIndex(
            model_name='glpicachedcomputer',
            index=models.Index(fields=['name'], name='catalog_glpi_comp_name_idx'),
        ),
    ]
